name = "megz"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "DATA_KV"
id = "01195924400548829cbd80bf60ada313"

[ai]
binding = "AI"

[triggers]
crons = ["0 0 * * *"]