name = "megz"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "DATA_KV"
id = "ff69992ea0034094913d4a6fa1e78075"

[triggers]
crons = ["0 0 * * *"]