name = "megz-standalone"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "DATA_KV"
id = "YOUR_KV_NAMESPACE_ID"

[vars]
SUPABASE_URL = ""
SUPABASE_KEY = ""

[triggers]
crons = ["0 0 * * *"]
